branch-defaults:
  dev:
    environment: coinme-admin-dev
    group_suffix: null
  master:
    environment: coinme-admin-dev
global:
  application_name: coinme-admin
  default_ec2_keyname: coinme-east
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
